CONFIG_NAME: private-pos
PRESET_BASE: mainnet

# Use unique fork versions to avoid clashing with built-in network presets.
GENESIS_FORK_VERSION: 0x10000000
ALTAIR_FORK_VERSION: 0x01020304
BELLATRIX_FORK_VERSION: 0x02030405
CAPELLA_FORK_VERSION: 0x03040506
DENEB_FORK_VERSION: 0x04050607
ELECTRA_FORK_VERSION: 0x05060708
FULU_FORK_VERSION: 0x06070809

ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_EPOCH: 18446744073709551615
FULU_FORK_EPOCH: 18446744073709551615

TERMINAL_TOTAL_DIFFICULTY: 0

MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
MIN_GENESIS_TIME: 0
GENESIS_DELAY: 0

SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32

ETH1_FOLLOW_DISTANCE: 1
